stages:
  labelling:
    cmd: python src/experiment/labelling.py data/csv/clinical-data.csv data/csv/pup.csv -o data/labels.csv
    deps:
    - data/csv/clinical-data.csv
    - data/csv/pup.csv
    - src/experiment/labelling.py
    outs:
    - data/labels.csv
  prepare:
    cmd: python src/experiment/prepare.py data/raw data/labels.csv data/prepared
    deps:
    - data/labels.csv
    - data/raw
    - src/experiment/prepare.py
    params:
    - prepare.seed
    - prepare.num_samples
    outs:
    - data/prepared
  extractframes:
    cmd: python src/experiment/images2frames.py data/prepared/labelled-images.csv data/prepared/scans data/frames
    deps:
    - data/prepared/labelled-images.csv
    - data/prepared/scans
    - src/experiment/images2frames.py
    params:
    - extractframes.n_frames
    outs:
    - data/frames
  evaluate:
    cmd: python src/experiment/evaluate.py data/frames data/evaluation
    deps:
    - data/frames
    - src/experiment/evaluate.py
    metrics:
    - data/evaluation/scores.json
    params:
    - evaluate.seed
    - evaluate.batch_size
    - evaluate.initial_learning_rate
    - evaluate.validation_split
    - evaluate.patience
    - evaluate.decay_rate
    - evaluate.max_epochs
    outs:
    - data/evaluation/weights.h5
  train:
    cmd: python src/experiment/train.py data/frames data/model
    deps:
    - data/frames
    - src/experiment/train.py
    params:
    - train.seed
    - train.batch_size
    - train.initial_learning_rate
    - train.decay_rate
    - train.epochs
    outs:
    - data/model/memento.h5
