stages:
  labelling:
    cmd: python src/labelling.py data/csv/clinical-data.csv data/csv/pup.csv -o data/labels.csv
    deps:
    - data/csv/clinical-data.csv
    - data/csv/pup.csv
    - src/labelling.py
    outs:
    - data/labels.csv
  prepare:
    cmd: python src/prepare.py data/raw data/labels.csv data/prepared
    deps:
    - data/labels.csv
    - data/raw
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.num_samples
    outs:
    - data/prepared
  extractframes:
    cmd: python src/images2frames.py data/prepared/labelled-images.csv data/prepared/scans data/frames
    deps:
    - data/prepared/labelled-images.csv
    - data/prepared/scans
    - src/images2frames.py
    params:
    - extractframes.n_frames
    outs:
    - data/frames
  train:
    cmd: python src/train.py data/prepared
    deps:
    - data/prepared
    - src/train.py
    params:
    - train.batch_size
    outs:
    - data/train
