prepare:
  seed: 1234
  num_samples: 20
extractframes:
  n_frames: 20
evaluate:
  seed: 1234
  batch_size: 128
  initial_learning_rate: 0.00005
  validation_split: 0.2
  decay_rate: 0.96
  patience: 35
  max_epochs: 10000
train:
  seed: 1234
  batch_size: 128
  initial_learning_rate: 0.00005
  decay_rate: 0.96
  epochs: 40
