apiVersion: v1
kind: Service
metadata:
  name: "memento-backend"
  labels:
    app: "memento-backend"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: "memento-backend"
