apiVersion: v1
kind: Service
metadata:
  name: "memento-backend"
  labels:
    app: "memento-backend"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: "memento-backend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "memento-backend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "memento-backend"
  template:
    metadata:
      labels:
        app: "memento-backend"
    spec:
      containers:
        - name: "memento-backend"
          image: "se4airegistry.azurecr.io/memento-backend"
          ports:
            - containerPort: 8080
