---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: memento
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: memento
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: memento
        tier: frontend
    spec:
      containers:
        - name: httpserver
          image: "espositoandrea/memento-frontend:0.0.1"
