on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n SE4AIRegistry -g SE4AIRegistry9770-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n SE4AIRegistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n SE4AIRegistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n SE4AIRegistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: se4airegistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Set up DVC
      uses: iterative/setup-dvc@v1

    - name: Pull trained model
      run: |
        export GDRIVE_CREDENTIALS_DATA='${{ secrets.GDRIVE_CREDENTIALS_DATA }}'
        dvc pull train

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t se4airegistry.azurecr.io/memento-backend:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push se4airegistry.azurecr.io/memento-backend:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_se4aicluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep se4aicluster848e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace se4aicluster848e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: se4aicluster848e
        container-registry-url: se4airegistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: se4aiclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: se4aicluster848e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          se4airegistry.azurecr.io/memento-backend:${{ github.sha }}
        imagepullsecrets: |
          se4aiclusterdockerauth   
